name: Generate Professional CV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpango-1.0-0 \
          libharfbuzz0b \
          libpangoft2-1.0-0 \
          libfontconfig1 \
          libcairo2 \
          libgdk-pixbuf2.0-0 \
          shared-mime-info
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate CV
      run: |
        python generate_professional_cv.py
    
    - name: Check if CV was generated
      run: |
        if [ -f "static/eugene_chekan_software_engineer_in_test_cv.pdf" ]; then
          echo "✅ CV PDF generated successfully"
          ls -la static/eugene_chekan_software_engineer_in_test_cv.pdf
        else
          echo "❌ CV PDF not found"
          exit 1
        fi
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the generated files
        git add static/eugene_chekan_software_engineer_in_test_cv.pdf
        git add cv_preview.html
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generate CV PDF [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 